# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Send

# Model Form Field configuration
form: $/gms/feedback/models/send/fields.yaml

# Model Class name
modelClass: Gms\Feedback\Models\Send

# Default redirect location
defaultRedirect: gms/feedback/sends

# Create page
create:
    title: Create Send
    redirect: gms/feedback/sends/update/:id
    redirectClose: gms/feedback/sends

# Update page
update:
    title: Edit Send
    redirect: gms/feedback/sends
    redirectClose: gms/feedback/sends

# Preview page
preview:
    title: Preview Send
