# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Filter Humidity Timer

# Model Form Field configuration
form: $/gms/settings/models/filterhumiditytimer/fields.yaml

# Model Class name
modelClass: Gms\Settings\Models\FilterHumidityTimer

# Default redirect location
defaultRedirect: gms/settings/filterhumiditytimers

# Create page
create:
    title: Create Filter Humidity Timer
    redirect: gms/settings/filterhumiditytimers/update/:id
    redirectClose: gms/settings/filterhumiditytimers

# Update page
update:
    title: Edit Filter Humidity Timer
    redirect: gms/settings/filterhumiditytimers
    redirectClose: gms/settings/filterhumiditytimers

# Preview page
preview:
    title: Preview Filter Humidity Timer
